steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-f',
        'scrapers/mercadona/scrape_daily/Dockerfile', # Path from the ROOT of the project
        '-t',
        '${_IMAGE_URI}',
        '.' # The context stays as dot (the root) so it can see the /scrapers folder
      ]

images:
  - '${_IMAGE_URI}'