version: 2

sources:
  - name: bronze
    database: lab-spanish-smarkts-scraper
    schema: dwh_bronze_dev
    tables:
      - name: bronze_alcampo_products_p
        description: "Raw bronze table for Alcampo supermarket products."
        columns:
          - name: product_url
            tests:
              - not_null
          - name: date
            tests:
              - not_null

      - name: bronze_carrefour_products_p
        description: "Raw bronze table for Carrefour supermarket products."
        columns:
          - name: product_url
            tests:
              - not_null
          - name: date
            tests:
              - not_null

      - name: bronze_dia_products_p
        description: "Raw bronze table for Dia supermarket products."
        columns:
          - name: product_url
            tests:
              - not_null
          - name: date
            tests:
              - not_null

      - name: bronze_mercadona_products_p
        description: "Raw bronze table for Mercadona supermarket products."
        columns:
          - name: product_url
            tests:
              - not_null
          - name: date
            tests:
              - not_null