name: 'supermarket_dwh'
version: '1.0.0'
config-version: 2

profile: 'supermarket_dwh'

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  supermarket_dwh:
    +materialized: table

    staging:
      +materialized: view

    intermediate:
      +materialized: table

    silver:
      +materialized: table

    gold:
      +materialized: table